[package]
name = "rili"
version = "0.1.0"
edition = "2021"
description = "本地优先的桌面日历 / 待办 / 便签工具，使用 Rust + Slint 构建"

[lib]
path = "src/lib.rs"

[[bin]]
name = "rili"
path = "src/main.rs"
test = false
bench = false

[dependencies]
slint = { version = "1.17.1", default-features = false, features = ["std", "compat-1-2", "backend-winit", "unstable-winit-030", "renderer-software", "renderer-femtovg", "accessibility"] }
rusqlite = { version = "0.40", features = ["bundled"] }
chrono = "0.4"
chinese-lunisolar-calendar = "0.2"
clap = { version = "4.6", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
directories = "6"
anyhow = "1"
tray-icon = "0.24"
ureq = { version = "2", default-features = false, features = ["tls", "gzip", "json"] }

[target.'cfg(windows)'.dependencies]
winrt-toast = "0.1"

[build-dependencies]
slint-build = "1.17.1"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true
panic = "abort"

[profile.dev]
debug = 0

[profile.test]
debug = 0
